import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import "tailwindcss/tailwind.css";
const inter = Inter({ subsets: ["latin"] });
import Head from "next/head";
export default function Home() {
	return (
		<div className={styles.main}>
			<Head>
				<title>logistics information system</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<button className="mx-0 rounded-full border border-purple-200 bg-white px-4 py-1 text-center text-sm hover:border-transparent hover:bg-pink-600 hover:text-white">
				Welcome to lis
			</button>
		</div>
	);
}
