import Head from 'next/head'

import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

import 'tailwindcss/tailwind.css'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <main className={styles.main}>
        <Head>
          <title>logistics information system</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className='container mx-auto'>
          <p className='text-5xl text-center'>Hello</p>
        </div>
      </main >
    </>
  )
}
